<?php
    define("MYSQL_LOGIN","root");
    define("MYSQL_PASSWORD","");
    define("MYSQL_SERVER","localhost");
    define("MYSQL_DB","birdibeuk_v2");
    define("PREFIX_DB","birdi_");
    define("ROOT",__DIR__."/../");
    define("DEBUG",true);
?>
